{
  "openapi": "3.0.2",
  "info": {
    "title": "DYGIADS BACKEND",
    "version": "1.0.0",
    "description": "DYGIADS BACKEND"
  },
  "paths": {
    "/users/": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              },
              "examples": {
                "CreateUser": {
                  "value": {
                    "name": "dummy",
                    "document": "123456",
                    "address": "dummy",
                    "complement": "dummy",
                    "state": "dummy",
                    "city": "dummy",
                    "password": "12345",
                    "email": "dummy3@dummy3.com.br"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/CreateUserResponse"
          },
          "400": {
            "$ref": "#/components/responses/GeneralError"
          },
          "404": {
            "$ref": "#/components/responses/GeneralError"
          },
          "500": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      }
    },
    "/users/{id}": {
      "put": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              },
              "examples": {
                "UpdateUserRequest": {
                  "value": {
                    "name": "editado",
                    "address": "editado",
                    "complement": "editado",
                    "state": "editado",
                    "city": "editado",
                    "password": "editado"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "updated user"
          },
          "400": {
            "$ref": "#/components/responses/GeneralError"
          },
          "404": {
            "$ref": "#/components/responses/GeneralError"
          },
          "500": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      },
      "parameters": [
        {
          "examples": {
            "userId": {
              "value": "1"
            }
          },
          "name": "id",
          "schema": {
            "type": "number"
          },
          "in": "path",
          "required": true
        },
        {
          "name": "authorization",
          "description": "token",
          "schema": {
            "type": "string"
          },
          "in": "header",
          "required": true
        }
      ]
    },
    "/auth/": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthRequest"
              },
              "examples": {
                "AuthUserRequest": {
                  "value": {
                    "email": "dummy3@dummy3.com.br",
                    "password": "12345"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/AuthResponse"
          },
          "204": {
            "$ref": "#/components/responses/GeneralError"
          },
          "400": {
            "$ref": "#/components/responses/GeneralError"
          },
          "500": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      }
    },
    "/companies/": {
      "get": {
        "parameters": [
          {
            "examples": {
              "authorization": {
                "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzeXN0ZW0tMUBzeXN0ZW0tMS5jb20iLCJyb2xlIjp7ImlkIjoyLCJuYW1lIjoiVVNFUiJ9LCJpYXQiOjE2NDMzMjc5MTUsImV4cCI6MTY0MzQxNDMxNX0.Mn9J3CNQGX4f-Rf2kd4uTe-NF5QPGJlsYNQB7pTyNn4"
              }
            },
            "name": "authorization",
            "description": "",
            "schema": {
              "type": "string"
            },
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/CompaniesResponse"
          },
          "204": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCompanyRequest"
              },
              "examples": {
                "CreateCompany": {
                  "value": {
                    "type": "dummy",
                    "corporationName": "dummy",
                    "email": "dummy",
                    "document": "wwweegfgf2",
                    "zipCode": "dummy",
                    "address": "dummy",
                    "number": "dummy",
                    "complement": "dummy",
                    "state": "dummy",
                    "city": "dummy"
                  }
                }
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "name": "authorization",
            "description": "",
            "schema": {
              "type": "string"
            },
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "$ref": "#/components/responses/CreateUserResponse"
          },
          "204": {
            "$ref": "#/components/responses/GeneralError"
          },
          "400": {
            "$ref": "#/components/responses/GeneralError"
          },
          "401": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      }
    },
    "/password-reset/": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PasswordResetRequest"
              },
              "examples": {
                "PasswordResetResponse": {
                  "value": {
                    "email": "dummy3@dummy3.com.br"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/PasswordResetResponse"
          },
          "204": {
            "$ref": "#/components/responses/GeneralError"
          },
          "404": {
            "$ref": "#/components/responses/GeneralError"
          },
          "500": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      }
    },
    "/campaigns/{id}": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "description": "company_id",
            "schema": {
              "type": "number"
            },
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/CampaignsOfCompany"
          },
          "400": {
            "$ref": "#/components/responses/GeneralError"
          },
          "404": {
            "$ref": "#/components/responses/GeneralError"
          },
          "500": {
            "$ref": "#/components/responses/GeneralError"
          }
        }
      },
      "parameters": [
        {
          "name": "id",
          "schema": {
            "type": "number"
          },
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "CreateUserRequest": {
        "title": "Root Type for CreateUserRequest",
        "description": "",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "document": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "name": "dummy",
          "document": "123456",
          "address": "dummy",
          "complement": "dummy",
          "state": "dummy",
          "city": "dummy",
          "password": "12345",
          "email": "dummy3@dummy3.com.br"
        }
      },
      "CreateUserResponse": {
        "title": "Root Type for CreateUserResponse",
        "description": "",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "document": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          }
        },
        "example": {
          "name": "dummy",
          "document": "123456",
          "address": "dummy",
          "complement": "dummy",
          "state": "dummy",
          "city": "dummy"
        }
      },
      "Error": {
        "title": "Root Type for Error",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "status": {
            "description": "",
            "type": "string"
          }
        },
        "example": {
          "message": "some text",
          "status": "some text"
        }
      },
      "UpdateUserRequest": {
        "title": "Root Type for UpdateUserRequest",
        "description": "",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "name": "editado",
          "address": "editado",
          "complement": "editado",
          "state": "editado",
          "city": "editado",
          "password": "editado"
        }
      },
      "AuthRequest": {
        "title": "Root Type for AuthRequest",
        "description": "",
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "dummy3@dummy3.com.br",
          "password": "12345"
        }
      },
      "AuthUserResponse": {
        "title": "Root Type for AuthUserResponse",
        "description": "",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "name": "dummy",
          "email": "dummy3@dummy3.com.br"
        }
      },
      "AuthResponse": {
        "description": "",
        "required": [
          "user",
          "token"
        ],
        "type": "object",
        "properties": {
          "user": {
            "$ref": "#/components/schemas/AuthUserResponse",
            "description": ""
          },
          "token": {
            "description": "",
            "type": "string"
          }
        },
        "example": {
          "user": {
            "name": "some text",
            "email": "some text"
          },
          "token": "some text"
        }
      },
      "CreateCompanyRequest": {
        "title": "Root Type for CreateCompanyRequest",
        "description": "",
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "corporationName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "document": {
            "type": "string"
          },
          "zipCode": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "number": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          }
        },
        "example": {
          "type": "dummy",
          "corporationName": "dummy",
          "email": "dummy",
          "document": "wwweegfgf",
          "zipCode": "dummy",
          "address": "dummy",
          "number": "dummy",
          "complement": "dummy",
          "state": "dummy",
          "city": "dummy"
        }
      },
      "CreateCompanyResponse": {
        "title": "Root Type for CreateCompanyResponse",
        "description": "",
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "corporationName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "document": {
            "type": "string"
          }
        },
        "example": {
          "type": "dummy",
          "corporationName": "dummy",
          "email": "dummy",
          "document": "wwweegfgf2"
        }
      },
      "Company": {
        "title": "Root Type for Company",
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "type": {
            "type": "string"
          },
          "corporationName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "document": {
            "type": "string"
          },
          "zipCode": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "number": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string"
          }
        },
        "example": {
          "id": 1,
          "type": "dummy",
          "corporationName": "dummy",
          "email": "dummy",
          "document": "wwweegfgf",
          "zipCode": "dummy",
          "address": "dummy",
          "number": "dummy",
          "complement": "dummy",
          "state": "dummy",
          "city": "dummy",
          "createdAt": "2022-01-27T00:37:44.623Z",
          "updatedAt": "2022-01-27T00:37:44.623Z"
        }
      },
      "PasswordResetRequest": {
        "title": "Root Type for PasswordResetRequest",
        "description": "",
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          }
        },
        "example": {
          "email": "dummy3@dummyw3.com.br"
        }
      },
      "PasswordResetResponse": {
        "title": "Root Type for PasswordResetResponse",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "message": "Recovery email sent",
          "email": "dummy3@dummy3.com.br"
        }
      },
      "CampaignRequest": {
        "title": "Root Type for CampaignRequest",
        "description": "",
        "type": "object",
        "properties": {
          "company_id": {
            "format": "int32",
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "start": {
            "format": "date",
            "type": "string"
          },
          "end": {
            "format": "date",
            "type": "string"
          }
        },
        "example": {
          "company_id": 1,
          "name": "mc boladao do meier",
          "start": "2022-02-15",
          "end": "2022-02-20"
        }
      },
      "CompanyCampaingResponse": {
        "title": "Root Type for CompanyCampaingResponse",
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "type": {
            "type": "string"
          },
          "corporationName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "document": {
            "type": "string"
          },
          "zipCode": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "number": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string"
          },
          "campaigns": {
            "type": "array",
            "items": {}
          }
        },
        "example": {
          "id": 1,
          "type": "dummy",
          "corporationName": "dummy",
          "email": "dummy",
          "document": "wwweegfgf",
          "zipCode": "dummy",
          "address": "dummy",
          "number": "dummy",
          "complement": "dummy",
          "state": "dummy",
          "city": "dummy",
          "createdAt": "2022-01-27T00:37:44.623Z",
          "updatedAt": "2022-01-27T00:37:44.623Z",
          "campaigns": []
        }
      },
      "CampaignResponse": {
        "title": "Root Type for CampaignResponse",
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "start": {
            "format": "date",
            "type": "string"
          },
          "end": {
            "format": "date",
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string"
          },
          "company": {
            "$ref": "#/components/schemas/CompanyCampaingResponse",
            "properties": {
              "id": {
                "format": "int32",
                "type": "integer"
              },
              "type": {
                "type": "string"
              },
              "corporationName": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "document": {
                "type": "string"
              },
              "zipCode": {
                "type": "string"
              },
              "address": {
                "type": "string"
              },
              "number": {
                "type": "string"
              },
              "complement": {
                "type": "string"
              },
              "state": {
                "type": "string"
              },
              "city": {
                "type": "string"
              },
              "createdAt": {
                "format": "date-time",
                "type": "string"
              },
              "updatedAt": {
                "format": "date-time",
                "type": "string"
              },
              "campaigns": {
                "type": "array",
                "items": {}
              }
            }
          },
          "announcementGroup": {
            "type": "string"
          }
        },
        "example": {
          "id": 1,
          "name": "mc boladao do meier",
          "start": "2022-02-15",
          "end": "2022-02-20",
          "createdAt": "2022-01-27T01:01:39.055Z",
          "updatedAt": "2022-01-27T01:01:39.055Z",
          "company": {
            "id": 1,
            "type": "dummy",
            "corporationName": "dummy",
            "email": "dummy",
            "document": "wwweegfgf",
            "zipCode": "dummy",
            "address": "dummy",
            "number": "dummy",
            "complement": "dummy",
            "state": "dummy",
            "city": "dummy",
            "createdAt": "2022-01-27T00:37:44.623Z",
            "updatedAt": "2022-01-27T00:37:44.623Z",
            "campaigns": []
          }
        }
      },
      "UpdateCampaignRequest": {
        "title": "Root Type for UpdateCampaignRequest",
        "description": "",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "start": {
            "format": "date",
            "type": "string"
          },
          "end": {
            "format": "date",
            "type": "string"
          }
        },
        "example": {
          "name": "editado",
          "start": "2023-12-29",
          "end": "2023-01-01"
        }
      },
      "AnnouncementRequest": {
        "title": "Root Type for AnnouncementRequest",
        "description": "",
        "type": "object",
        "properties": {
          "duration": {
            "format": "int32",
            "type": "integer"
          },
          "format": {
            "enum": [
              "PANEL",
              "PORTAL"
            ],
            "type": "string"
          }
        },
        "example": {
          "duration": 10,
          "format": "PORTAL"
        }
      },
      "AnnouncementResponse": {
        "title": "Root Type for AnnouncementResponse",
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "duration": {
            "format": "int32",
            "type": "integer"
          },
          "format": {
            "format": "int32",
            "type": "integer"
          },
          "frequency": {
            "type": "string"
          }
        },
        "example": {
          "id": 1,
          "duration": 900,
          "format": 0,
          "frequency": "60S"
        }
      },
      "SemaphoreRequest": {
        "title": "Root Type for SemaphoreRequest",
        "description": "",
        "type": "object",
        "properties": {
          "street": {
            "type": "string"
          },
          "lat": {
            "type": "string"
          },
          "lng": {
            "type": "string"
          },
          "cep": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          }
        },
        "example": {
          "street": "rua das flores",
          "lat": "123",
          "lng": "321",
          "cep": "cep",
          "reference": "sem teto"
        }
      },
      "SemaphoreResponse": {
        "title": "Root Type for SemaphoreResponse",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "Semaphore created successfully"
        }
      },
      "Schedule": {
        "title": "Root Type for Schedule",
        "description": "",
        "required": [
          "plan"
        ],
        "type": "object",
        "properties": {
          "weekday": {
            "enum": [
              "Monday|Tuesday|Wednesday|Thursday|Friday",
              "Saturday|Sunday"
            ],
            "type": "string"
          },
          "start": {
            "type": "string"
          },
          "end": {
            "type": "string"
          },
          "plan": {
            "$ref": "#/components/schemas/Plan",
            "properties": {
              "green": {
                "format": "int32",
                "type": "integer"
              },
              "yellow": {
                "format": "int32",
                "type": "integer"
              },
              "red": {
                "format": "int32",
                "type": "integer"
              }
            }
          }
        },
        "example": {
          "weekday": "Monday|Tuesday|Wednesday|Thursday|Friday",
          "start": "0",
          "end": "10",
          "plan": {
            "green": 60,
            "yellow": 5,
            "red": 69
          }
        }
      },
      "Plan": {
        "title": "Root Type for Plan",
        "description": "",
        "type": "object",
        "properties": {
          "green": {
            "format": "int32",
            "type": "integer"
          },
          "yellow": {
            "format": "int32",
            "type": "integer"
          },
          "red": {
            "format": "int32",
            "type": "integer"
          }
        },
        "example": {
          "green": 60,
          "yellow": 5,
          "red": 69
        }
      },
      "ScheduleRequest": {
        "title": "Root Type for ScheduleRequest",
        "description": "",
        "type": "object",
        "properties": {
          "schedules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Schedule"
            }
          },
          "semaphore": {
            "format": "int32",
            "type": "integer"
          }
        },
        "example": {
          "schedules": [
            {
              "weekday": "Monday|Tuesday|Wednesday|Thursday|Friday",
              "start": "0",
              "end": "10",
              "plan": {
                "green": 60,
                "yellow": 5,
                "red": 69
              }
            },
            {
              "weekday": "Monday|Tuesday|Wednesday|Thursday|Friday",
              "start": "10",
              "end": "18",
              "plan": {
                "green": 60,
                "yellow": 5,
                "red": 69
              }
            },
            {
              "weekday": "Monday|Tuesday|Wednesday|Thursday|Friday",
              "start": "18",
              "end": "23",
              "plan": {
                "green": 60,
                "yellow": 5,
                "red": 69
              }
            },
            {
              "weekday": "Saturday|Sunday",
              "start": "0",
              "end": "5",
              "plan": {
                "green": 60,
                "yellow": 5,
                "red": 69
              }
            },
            {
              "weekday": "Saturday|Sunday",
              "start": "5",
              "end": "23",
              "plan": {
                "green": 60,
                "yellow": 5,
                "red": 69
              }
            }
          ],
          "semaphore": 1
        }
      },
      "ScheduleResponse": {
        "title": "Root Type for ScheduleResponse",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "Schedule created successfully"
        }
      },
      "SlotRequest": {
        "title": "Root Type for SlotRequest",
        "description": "",
        "type": "object",
        "properties": {
          "year": {
            "format": "int32",
            "type": "integer"
          },
          "month": {
            "format": "int32",
            "type": "integer"
          }
        },
        "example": {
          "year": 2022,
          "month": 1
        }
      },
      "SlotResponse": {
        "title": "Root Type for SlotResponse",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "slot created successfully"
        }
      },
      "SemaphoreSituationRequest": {
        "title": "Root Type for SemaphoreSituation",
        "description": "",
        "type": "object",
        "properties": {
          "yellow": {
            "format": "int32",
            "type": "integer"
          },
          "red": {
            "format": "int32",
            "type": "integer"
          },
          "green": {
            "format": "int32",
            "type": "integer"
          }
        },
        "example": {
          "yellow": 5,
          "red": 100,
          "green": 60
        }
      },
      "SemaphoreSituationResponse": {
        "title": "Root Type for SemaphoreSituationResponse",
        "description": "",
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "example": {
          "message": "ok"
        }
      },
      "HealthCheckResponse": {
        "title": "Root Type for HealthCheckResponse",
        "description": "",
        "type": "object",
        "properties": {
          "ok": {
            "type": "boolean"
          }
        },
        "example": {
          "ok": true
        }
      },
      "HealthCheckStatusResponse": {
        "title": "Root Type for HealthCheckStatus",
        "description": "",
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "OK",
          "message": "Health Status Semaphore Controller"
        }
      },
      "CampaignsOfCompany": {
        "title": "Root Type for CampaignsOfCompany",
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "start": {
            "format": "date-time",
            "type": "string"
          },
          "end": {
            "format": "date-time",
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string"
          }
        },
        "example": {
          "id": 1,
          "name": "mc boladao do meier",
          "start": "2022-02-15T00:00:00.000Z",
          "end": "2022-02-20T00:00:00.000Z",
          "createdAt": "2022-02-03T02:05:31.672Z",
          "updatedAt": "2022-02-03T02:05:31.672Z"
        }
      },
      "CreatedFile": {
        "title": "Root Type for CreatedFile",
        "description": "",
        "type": "object",
        "properties": {
          "fileId": {
            "type": "string"
          },
          "fileName": {
            "type": "string"
          }
        },
        "example": {
          "fileId": "lala.mp4",
          "fileName": "lalala"
        }
      }
    },
    "responses": {
      "CreateUserResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CreateUserResponse"
            },
            "examples": {
              "CreateUserResponse": {
                "value": {
                  "name": "some text",
                  "document": "some text",
                  "address": "some text",
                  "complement": "some text",
                  "state": "some text",
                  "city": "some text"
                }
              }
            }
          }
        },
        "description": ""
      },
      "GeneralError": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        },
        "description": ""
      },
      "AuthResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/AuthResponse"
            },
            "examples": {
              "AuthResponse": {
                "value": {
                  "user": {
                    "name": "dummy",
                    "email": "dummy3@dummy3.com.br"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkdW1teTNAZHVtbXkzLmNvbS5iciIsInJvbGUiOnsiaWQiOjIsIm5hbWUiOiJVU0VSIn0sImlhdCI6MTY0MzI0MzA5MiwiZXhwIjoxNjQzMzI5NDkyfQ.-ZzqCzIgyXKrefsknG6ynoNyvaDM9D0G7shLS0Sc2MI"
                }
              }
            }
          }
        },
        "description": ""
      },
      "CreateCompanyResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CreateCompanyResponse"
            },
            "examples": {
              "CreateCompanyResponse": {
                "value": {
                  "type": "dummy",
                  "corporationName": "dummy",
                  "email": "dummy",
                  "document": "wwweegfgf2"
                }
              }
            }
          }
        },
        "description": ""
      },
      "CompaniesResponse": {
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/Company"
              }
            },
            "examples": {
              "Companies": {
                "value": [
                  {
                    "id": 1,
                    "type": "dummy",
                    "corporationName": "dummy",
                    "email": "dummy",
                    "document": "wwweegfgf",
                    "zipCode": "dummy",
                    "address": "dummy",
                    "number": "dummy",
                    "complement": "dummy",
                    "state": "dummy",
                    "city": "dummy",
                    "createdAt": "2022-01-27T00:37:44.623Z",
                    "updatedAt": "2022-01-27T00:37:44.623Z"
                  },
                  {
                    "id": 2,
                    "type": "dummy",
                    "corporationName": "dummy",
                    "email": "dummy",
                    "document": "wwweegfgf2",
                    "zipCode": "dummy",
                    "address": "dummy",
                    "number": "dummy",
                    "complement": "dummy",
                    "state": "dummy",
                    "city": "dummy",
                    "createdAt": "2022-01-27T00:38:16.795Z",
                    "updatedAt": "2022-01-27T00:38:16.795Z"
                  }
                ]
              }
            }
          }
        },
        "description": ""
      },
      "PasswordResetResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PasswordResetResponse"
            },
            "examples": {
              "PasswordResetResponse": {
                "value": {
                  "message": "Recovery email sent",
                  "email": "dummy3@dummy3.com.br"
                }
              }
            }
          }
        },
        "description": ""
      },
      "CreateCampaignResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CampaignResponse"
            },
            "examples": {
              "CreateCampaign": {
                "value": {
                  "id": 2,
                  "name": "mc boladao do meier",
                  "start": "2022-02-15",
                  "end": "2022-02-20",
                  "createdAt": "2022-01-27T01:10:22.669Z",
                  "updatedAt": "2022-01-27T01:10:22.669Z",
                  "company": {
                    "id": 1,
                    "type": "dummy",
                    "corporationName": "dummy",
                    "email": "dummy",
                    "document": "wwweegfgf",
                    "zipCode": "dummy",
                    "address": "dummy",
                    "number": "dummy",
                    "complement": "dummy",
                    "state": "dummy",
                    "city": "dummy",
                    "createdAt": "2022-01-27T00:37:44.623Z",
                    "updatedAt": "2022-01-27T00:37:44.623Z",
                    "campaigns": [
                      {
                        "id": 1,
                        "name": "mc boladao do meier",
                        "start": "2022-02-15T00:00:00.000Z",
                        "end": "2022-02-20T00:00:00.000Z",
                        "createdAt": "2022-01-27T01:01:39.055Z",
                        "updatedAt": "2022-01-27T01:01:39.055Z"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "description": ""
      },
      "AnnoucementeResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/AnnouncementResponse"
            },
            "examples": {
              "AnnouncementResponse": {
                "value": {
                  "id": 1,
                  "duration": 900,
                  "format": 0,
                  "frequency": "60S"
                }
              }
            }
          }
        },
        "description": ""
      },
      "SemaphoreResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SemaphoreResponse"
            },
            "examples": {
              "SemaphoreResponse": {
                "value": {
                  "message": "Semaphore created successfully"
                }
              }
            }
          }
        },
        "description": ""
      },
      "ScheduleResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ScheduleResponse"
            },
            "examples": {
              "ScheduleResponse": {
                "value": {
                  "message": "Schedule created successfully"
                }
              }
            }
          }
        },
        "description": ""
      },
      "SlotResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SlotResponse"
            },
            "examples": {
              "SlotResponse": {
                "value": {
                  "message": "slot created successfully"
                }
              }
            }
          }
        },
        "description": ""
      },
      "SemaphoreSituationResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SemaphoreSituationResponse"
            },
            "examples": {
              "SemaphoreSituationResponse": {
                "value": {
                  "message": "ok"
                }
              }
            }
          }
        },
        "description": ""
      },
      "HealthCheckResponse": {
        "headers": {
          "authorization": {
            "schema": {
              "type": "string"
            },
            "examples": {
              "authorization": {
                "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzeXN0ZW0tMUBzeXN0ZW0tMS5jb20iLCJyb2xlIjp7ImlkIjoxLCJuYW1lIjoiU1lTVEVNIn0sImlhdCI6MTY0MzI0ODUwNywiZXhwIjoxNjQzMzM0OTA3fQ.OZeqaFaXQE3WVCV76PChXLTdz4uQnGrSDBkAcfaRYzg"
              }
            }
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HealthCheckResponse"
            },
            "examples": {
              "HealthCheck": {
                "value": {
                  "ok": true
                }
              }
            }
          }
        },
        "description": ""
      },
      "HealthCheckStatusResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HealthCheckStatusResponse"
            },
            "examples": {
              "HealthCheckStatusResponse": {
                "value": {
                  "status": "some text",
                  "message": "some text"
                }
              }
            }
          }
        },
        "description": ""
      },
      "CampaignsOfCompany": {
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/CampaignsOfCompany"
              }
            },
            "examples": {
              "Campaigns": {
                "value": [
                  {
                    "id": 1,
                    "name": "mc boladao do meier",
                    "start": "2022-02-15T00:00:00.000Z",
                    "end": "2022-02-20T00:00:00.000Z",
                    "createdAt": "2022-02-03T02:05:31.672Z",
                    "updatedAt": "2022-02-03T02:05:31.672Z"
                  },
                  {
                    "id": 2,
                    "name": "mc boladao do meier",
                    "start": "2022-02-15T00:00:00.000Z",
                    "end": "2022-02-20T00:00:00.000Z",
                    "createdAt": "2022-02-03T02:17:41.367Z",
                    "updatedAt": "2022-02-03T02:17:41.367Z"
                  }
                ]
              }
            }
          }
        },
        "description": ""
      },
      "CreatedFileResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CreatedFile"
            },
            "examples": {
              "CreatedFile": {
                "value": {
                  "fileId": "some text",
                  "fileName": "some text"
                }
              }
            }
          }
        },
        "description": ""
      }
    }
  }
}